=== ArabSkillsNetwork/BedrockBlockUpgradeSchema/nbt_upgrade_schema_schema.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"$defs": {
		"blockStateProperty": {
			"type": "object",
			"minProperties": 1,
			"maxProperties": 1,
			"additionalProperties": false,
			"properties": {
				"int": {
					"type": "integer"
				},
				"string": {
					"type": "string"
				},
				"byte": {
					"type": "integer"
				}
			}
		},
		"flattenRule": {
			"type": "object",
			"required": [
				"prefix",
				"flattenedProperty",
				"suffix"
			],
			"properties": {
				"prefix": {
					"type": "string"
				},
				"flattenedProperty": {
					"type": "string"
				},
				"flattenedPropertyType": {
					"type": "string",
					"enum": ["int", "string", "byte"]
				},
				"suffix": {
					"type": "string"
				},
				"flattenedValueRemaps": {
					"type": "object",
					"additionalProperties": {
						"type": "string"
					}
				}
			},
			"additionalProperties": false
		}
	},
	"type": "object",
	"additionalProperties": false,
	"required": [
		"maxVersionMajor",
		"maxVersionMinor",
		"maxVersionPatch",
		"maxVersionRevision"
	],
	"properties": {
		"maxVersionMajor": {
			"type": "integer",
			"minimum": 0
		},
		"maxVersionMinor": {
			"type": "integer",
			"minimum": 0
		},
		"maxVersionPatch": {
			"type": "integer",
			"minimum": 0
		},
		"maxVersionRevision": {
			"type": "integer",
			"minimum": 0
		},
		"forceApplyAddedProperties": {
			"type": "boolean"
		},
		"renamedIds": {
			"type": "object",
			"additionalProperties": {
				"type": "string"
			}
		},
		"renamedProperties": {
			"type": "object",
			"additionalProperties": {
				"type": "object",
				"additionalProperties": {
					"type": "string"
				}
			}
		},
		"addedProperties": {
			"type": "object",
			"additionalProperties": {
				"type": "object",
				"additionalProperties": {
					"$ref": "#/$defs/blockStateProperty"
				}
			}
		},
		"removedProperties": {
			"type": "object",
			"additionalProperties": {
				"type": "array",
				"items": {
					"type": "string"
				}
			}
		},
		"remappedPropertyValues": {
			"type": "object",
			"additionalProperties": {
				"type": "object",
				"additionalProperties": {
					"type": "string"
				}
			}
		},
		"remappedPropertyValuesIndex": {
			"type": "object",
			"additionalProperties": {
				"type": "array",
				"items": {
					"type": "object",
					"properties": {
						"old": {
							"$ref": "#/$defs/blockStateProperty"
						},
						"new": {
							"$ref": "#/$defs/blockStateProperty"
						}
					},
					"additionalProperties": false
				}
			}
		},
		"flattenedProperties": {
			"type": "object",
			"additionalProperties": {
				"$ref": "#/$defs/flattenRule"
			}
		},
		"remappedStates": {
			"type": "object",
			"additionalProperties": {
				"type": "array",
				"items": {
					"type": "object",
					"required": [
						"oldState",
						"newState"
					],
					"oneOf": [
						{
							"required": ["newName"]
						},
						{
							"required": ["newFlattenedName"]
						}
					],
					"properties": {
						"oldState": {
							"type": ["object", "null"],
							"additionalProperties": {
								"$ref": "#/$defs/blockStateProperty"
							}
						},
						"newName": {
							"type": "string"
						},
						"newFlattenedName": {
							"$ref": "#/$defs/flattenRule"
						},
						"newState": {
							"type": ["object", "null"],
							"additionalProperties": {
								"$ref": "#/$defs/blockStateProperty"
							}
						},
						"copiedState": {
							"type": "array",
							"items": {
								"type": "string"
							}
						}
					},
					"additionalProperties": false
				}
			}
		}
	}
}

=== ArabSkillsNetwork/BedrockBlockUpgradeSchema/nbt_upgrade_schema/0331_1.21.100.23_beta_to_1.21.110.26_beta.json
{
    "maxVersionMajor": 1,
    "maxVersionMinor": 21,
    "maxVersionPatch": 60,
    "maxVersionRevision": 33,
    "forceApplyAddedProperties": true,
    "renamedIds": {
        "minecraft:chain": "minecraft:iron_chain"
    },
    "addedProperties": {
        "minecraft:lightning_rod": {
            "powered_bit": {
                "byte": 0
            }
        }
    }
}

=== ArabSkillsNetwork/BedrockBlockUpgradeSchema/nbt_upgrade_schema/0361_1.26.50_to_1.26.60.json
{
    "maxVersionMajor": 1,
    "maxVersionMinor": 21,
    "maxVersionPatch": 60,
    "maxVersionRevision": 33,
    "forceApplyAddedProperties": true,
    "addedProperties": {
        "minecraft:chorus_plant": {
            "minecraft:connection_down": {
                "byte": 0
            },
            "minecraft:connection_east": {
                "byte": 0
            },
            "minecraft:connection_north": {
                "byte": 0
            },
            "minecraft:connection_south": {
                "byte": 0
            },
            "minecraft:connection_up": {
                "byte": 0
            },
            "minecraft:connection_west": {
                "byte": 0
            }
        },
        "minecraft:fire": {
            "minecraft:connection_east": {
                "byte": 0
            },
            "minecraft:connection_north": {
                "byte": 0
            },
            "minecraft:connection_south": {
                "byte": 0
            },
            "minecraft:connection_up": {
                "byte": 0
            },
            "minecraft:connection_west": {
                "byte": 0
            }
        },
        "minecraft:redstone_wire": {
            "redstone_east": {
                "string": "none"
            },
            "redstone_north": {
                "string": "none"
            },
            "redstone_south": {
                "string": "none"
            },
            "redstone_west": {
                "string": "none"
            }
        }
    }
}
